-- 1. Crea la tabella "vital_signs"
CREATE TABLE public.vital_signs (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
                                    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- I parametri vitali (possono essere null se non forniti)
                                    pressione_sistolica INT,
                                    pressione_diastolica INT,
                                    frequenza_cardiaca INT,
                                    saturazione_ossigeno INT,

    -- Il braccio usato (come da roadmap)
                                    braccio TEXT, -- 'destro', 'sinistro', 'non specificato'

    -- Il commento di Lisa (come da roadmap, per import/export)
                                    commento_lisa TEXT
);

-- 2. Attiva la Row Level Security (RLS)
ALTER TABLE public.vital_signs ENABLE ROW LEVEL SECURITY;

-- 3. Crea le policy di sicurezza
-- Gli utenti possono vedere e creare SOLO I LORO dati
CREATE POLICY "Gli utenti possono gestire i propri parametri vitali."
  ON public.vital_signs
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 4. (Opzionale ma consigliato) Crea un indice per velocizzare le query
CREATE INDEX idx_vital_signs_user_id_created_at
    ON public.vital_signs (user_id, created_at DESC);