-- 1. Crea la tabella "chat_messages"
CREATE TABLE public.chat_messages (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
                                      created_at TIMESTAMPTZ DEFAULT NOW(),
                                      role TEXT NOT NULL, -- 'user' o 'assistant'
                                      content TEXT NOT NULL
);

-- 2. Attiva la Row Level Security (RLS)
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

-- 3. Crea le policy di sicurezza
-- Gli utenti possono vedere e creare SOLO I LORO messaggi
CREATE POLICY "Utenti possono gestire i loro messaggi."
  ON public.chat_messages
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- 4. (Opzionale ma consigliato) Crea un indice per velocizzare le query
CREATE INDEX idx_chat_messages_user_id_created_at
    ON public.chat_messages (user_id, created_at DESC);